import { after, before, test } from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import EmbeddedPostgres from "embedded-postgres";
import { Pool } from "pg";
import { ExecutionQualityStore } from "../src/executionQuality/store";
import { fixture } from "./fixtures/executionQuality";
let pg: EmbeddedPostgres;
let pool: Pool;
let dir: string;
before(async () => {
  dir = await mkdtemp(join(tmpdir(),"execution-quality-pg-"));
  pg = new EmbeddedPostgres({ databaseDir:dir,user:"postgres",password:"postgres",port:55439,persistent:false,onLog:()=>{},onError:()=>{} });
  await pg.initialise(); await pg.start();
  pool = new Pool({host:"127.0.0.1",port:55439,user:"postgres",password:"postgres",database:"postgres"});
  const sql = await readFile("drizzle/2026-09-20_execution_quality.sql","utf8");
  await pool.query(sql); await pool.query(sql);
});
after(async () => { if (pool) await pool.end(); if (pg) await pg.stop(); if (dir) await rm(dir,{recursive:true,force:true}); });
test("migration, concurrent retry, roundtrip, restart, append-only and atomic conflicts", async () => {
  const first = new ExecutionQualityStore(pool), b = fixture();
  const results = await Promise.all([first.append(b),first.append(b)]);
  assert.equal(results.reduce((s,r)=>s+r.inserted,0),5);
  const restarted = new ExecutionQualityStore(pool);
  assert.equal((await restarted.append(b)).inserted,0);
  const out = await restarted.report(0,20000,20000);
  assert.equal(out.orderCount,1); assert.equal(out.groups[0].fillCount,2);
  const past = await restarted.report(0,11500,12000);
  assert.equal(past.groups[0].fillCount,1);
  await assert.rejects(() => pool.query("UPDATE execution_quality_events SET kind='fill'"),/append-only/);
  await assert.rejects(() => pool.query("DELETE FROM execution_quality_intents"),/append-only/);
  const conflict = fixture(); conflict.intent.quantity = 11;
  await assert.rejects(() => restarted.append(conflict),/INTENT_CONFLICT/);
  const duplicate = fixture(); duplicate.intent.id = "intent-2"; duplicate.intent.clientOrderId = "client-2";
  duplicate.events = duplicate.events.map(e=>({...e,intentId:"intent-2"}));
  await assert.rejects(() => restarted.append(duplicate),/unique constraint/);
  assert.equal((await pool.query("SELECT count(*)::int AS n FROM execution_quality_intents")).rows[0].n,1);
  assert.deepEqual(await restarted.report(0,20000,20000),out);
  const fill = b.events.find(e=>e.kind==="fill")!;
  await assert.rejects(() => restarted.append({intent:b.intent,events:[{...fill,fillId:"overfill"}]}),/OVERFILL/);
});
